#pragma once

enum EntityState
{
    ENTITY_STATE_IDLE,
    ENTITY_STATE_ON_GROUND,
    ENTITY_STATE_JUMPING,
    ENTITY_STATE_FALLING,
    
    ENTITY_STATE_DYING,
    ENTITY_STATE_TO_BE_REMOVED,

    ENTITY_STATE_VICTORY_DANCE
};  