#pragma once

enum MarioState
{
    MARIO_STATE_SMALL,
    MARIO_STATE_BIG,
    MARIO_STATE_FIRE,

    MARIO_STATE_TRANSFORMING_SMALL_TO_BIG,
    MARIO_STATE_TRANSFORMING_BIG_TO_SMALL,
    MARIO_STATE_TRANSFORMING_BIG_TO_FIRE,
    MARIO_STATE_TRANSFORMING_FIRE_TO_BIG,
    MARIO_STATE_TRANSFORMING_SMALL_TO_FIRE
};